// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpqCcllOsdbcu_K7h2KlxyN150ib8hsHw',
    appId: '1:248871298046:web:68ee1f48a89a9e614d56af',
    messagingSenderId: '248871298046',
    projectId: 'pokegame-bae4e',
    authDomain: 'pokegame-bae4e.firebaseapp.com',
    storageBucket: 'pokegame-bae4e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiAKlJYUqStptjKBFYLBBJLg4prNV4mTY',
    appId: '1:248871298046:android:d50dd5138bf2fdf44d56af',
    messagingSenderId: '248871298046',
    projectId: 'pokegame-bae4e',
    storageBucket: 'pokegame-bae4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUrStrAUSm7YtsMHjH0wZKPk11Kl32A3Y',
    appId: '1:248871298046:ios:bc1993d851cd0d944d56af',
    messagingSenderId: '248871298046',
    projectId: 'pokegame-bae4e',
    storageBucket: 'pokegame-bae4e.firebasestorage.app',
    iosBundleId: 'com.example.pokegame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUrStrAUSm7YtsMHjH0wZKPk11Kl32A3Y',
    appId: '1:248871298046:ios:bc1993d851cd0d944d56af',
    messagingSenderId: '248871298046',
    projectId: 'pokegame-bae4e',
    storageBucket: 'pokegame-bae4e.firebasestorage.app',
    iosBundleId: 'com.example.pokegame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpqCcllOsdbcu_K7h2KlxyN150ib8hsHw',
    appId: '1:248871298046:web:0d5eff4000b713b24d56af',
    messagingSenderId: '248871298046',
    projectId: 'pokegame-bae4e',
    authDomain: 'pokegame-bae4e.firebaseapp.com',
    storageBucket: 'pokegame-bae4e.firebasestorage.app',
  );
}
